function result = REDCap_report(conn,  report_id)
%% REDCap_report - Download report
  report_id = sprintf('%d', report_id);
  ops = weboptions('CertificateFilename', '', 'Debug', false);
  result = webwrite(conn.url, 'token', conn.token, 
    'content', 'report', ...
    'report_id', report_id, ...
    'format','csv', ...
    'returnFormat','csv', ...
    ops);
  result = table_format(result, conn.table_format);
end